// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR7uRIsQ5ZifhFAKoRL4IY0-bMjVTuA3Y',
    appId: '1:210083348003:web:f68c40cfdd132bd2787b96',
    messagingSenderId: '210083348003',
    projectId: 'farmacia-medicamentos',
    authDomain: 'farmacia-medicamentos.firebaseapp.com',
    storageBucket: 'farmacia-medicamentos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeHtyO0dLwtuHQ1nZ1WmP2jXbr3HLN42k',
    appId: '1:210083348003:android:03db8eed7f0f3f87787b96',
    messagingSenderId: '210083348003',
    projectId: 'farmacia-medicamentos',
    storageBucket: 'farmacia-medicamentos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMhbBZ0_QkHxyLQqv_gf3dH-ALlcGZLI8',
    appId: '1:210083348003:ios:e37e59434a274190787b96',
    messagingSenderId: '210083348003',
    projectId: 'farmacia-medicamentos',
    storageBucket: 'farmacia-medicamentos.firebasestorage.app',
    iosBundleId: 'com.example.farmaciaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMhbBZ0_QkHxyLQqv_gf3dH-ALlcGZLI8',
    appId: '1:210083348003:ios:e37e59434a274190787b96',
    messagingSenderId: '210083348003',
    projectId: 'farmacia-medicamentos',
    storageBucket: 'farmacia-medicamentos.firebasestorage.app',
    iosBundleId: 'com.example.farmaciaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR7uRIsQ5ZifhFAKoRL4IY0-bMjVTuA3Y',
    appId: '1:210083348003:web:c8412e9deded3adb787b96',
    messagingSenderId: '210083348003',
    projectId: 'farmacia-medicamentos',
    authDomain: 'farmacia-medicamentos.firebaseapp.com',
    storageBucket: 'farmacia-medicamentos.firebasestorage.app',
  );
}
